# Generated by Django 4.1.7 on 2023-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQTT_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='humm',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='temperatuerr',
            new_name='temperature',
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
