# Generated by Django 4.1.7 on 2023-04-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQTT_app', '0002_rename_humm_post_humidity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='weatherrr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.BigIntegerField()),
                ('hum', models.BigIntegerField()),
                ('wind', models.BigIntegerField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
