# Generated by Django 4.2 on 2023-04-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQTT_app', '0003_weatherrr'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wind',
            field=models.BigIntegerField(default=0),
        ),
    ]
